##ajouter ce que tu veux et la mapper avec la lib
my:
  kafka:
    consumer:
      enabled: true
      topic: test-younes
      groupId: my-group-id
      clientId: myclientIdyou
      #bootstrap-servers: local:5555
spring:
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  application:
    name: consumer-kafka




