apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-customer
  labels:
    app: elk-customer
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: elk-customer
  template:
    metadata:
      labels:
        app: elk-customer
    spec:
      containers:
      - name: elk-customer
        image: dokeryelmariki/elk-customer:latest
        ports:
        - containerPort: 8889
        
---
apiVersion: v1
kind: Service
metadata:
  name: elk-customer-service
  labels:
    app: elk-customer
spec:
  selector:
    app: elk-customer
  ports:
    - name: http
      port: 8889
      targetPort: 8889
  type: LoadBalancer
  